epoch: 12

LearningRate:
  base_lr: 0.000025
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones: [8, 11]
  - !LinearWarmup
    start_factor: 0.001
    steps: 1000

OptimizerBuilder:
  optimizer:
    type: AdamW
    weight_decay: 0.0001
